import {
  Users, ShoppingCart, Package, UserCircle, Box, LogIn, Boxes,
  Factory, Receipt, Truck, CreditCard, Star, BarChart, Megaphone,
  Headphones as HeadphonesIcon, FolderKanban, CheckSquare, FileText,
  Calendar, Book as AddressBook, MapPin, Clock, FileBarChart, Settings,
  MessageSquare, Bell, UserCog, Shield, FolderTree, Tag, GitBranch,
  Building2, Building, FileSpreadsheet, DollarSign, PieChart, Timer,
  GraduationCap, Award, MessageCircle
} from 'lucide-react';
import type { BusinessObject } from './types';

export const businessObjects: BusinessObject[] = [
  { id: '1', name: 'Employee', color: '#3B82F6', icon: Users },
  { id: '2', name: 'Order', color: '#10B981', icon: ShoppingCart },
  { id: '3', name: 'Product', color: '#F59E0B', icon: Package },
  { id: '4', name: 'Customer', color: '#6366F1', icon: UserCircle },
  { id: '5', name: 'Item', color: '#EC4899', icon: Box },
  { id: '6', name: 'Login Event', color: '#8B5CF6', icon: LogIn },
  { id: '7', name: 'Inventory', color: '#14B8A6', icon: Boxes },
  { id: '8', name: 'Supplier', color: '#EF4444', icon: Factory },
  { id: '9', name: 'Invoice', color: '#F97316', icon: Receipt },
  { id: '10', name: 'Shipment', color: '#06B6D4', icon: Truck },
  { id: '11', name: 'Payment', color: '#8B5CF6', icon: CreditCard },
  { id: '12', name: 'Review', color: '#22C55E', icon: Star },
  { id: '13', name: 'Analytics', color: '#9333EA', icon: BarChart },
  { id: '14', name: 'Marketing', color: '#DB2777', icon: Megaphone },
  { id: '15', name: 'Support', color: '#2DD4BF', icon: HeadphonesIcon },
  { id: '16', name: 'Project', color: '#F472B6', icon: FolderKanban },
  { id: '17', name: 'Task', color: '#FB923C', icon: CheckSquare },
  { id: '18', name: 'Document', color: '#4ADE80', icon: FileText },
  { id: '19', name: 'Meeting', color: '#A855F7', icon: Calendar },
  { id: '20', name: 'Contact', color: '#38BDF8', icon: AddressBook },
  { id: '21', name: 'Location', color: '#FB7185', icon: MapPin },
  { id: '22', name: 'Schedule', color: '#34D399', icon: Clock },
  { id: '23', name: 'Report', color: '#818CF8', icon: FileBarChart },
  { id: '24', name: 'Setting', color: '#F43F5E', icon: Settings },
  { id: '25', name: 'Message', color: '#8B5CF6', icon: MessageSquare },
  { id: '26', name: 'Notification', color: '#10B981', icon: Bell },
  { id: '27', name: 'Role', color: '#F59E0B', icon: UserCog },
  { id: '28', name: 'Permission', color: '#6366F1', icon: Shield },
  { id: '29', name: 'Category', color: '#EC4899', icon: FolderTree },
  { id: '30', name: 'Tag', color: '#14B8A6', icon: Tag },
  { id: '31', name: 'Workflow', color: '#3B82F6', icon: GitBranch },
  { id: '32', name: 'Department', color: '#10B981', icon: Building2 },
  { id: '33', name: 'Branch', color: '#F59E0B', icon: Building },
  { id: '34', name: 'Asset', color: '#6366F1', icon: FileSpreadsheet },
  { id: '35', name: 'Contract', color: '#EC4899', icon: FileText },
  { id: '36', name: 'Expense', color: '#8B5CF6', icon: DollarSign },
  { id: '37', name: 'Revenue', color: '#14B8A6', icon: PieChart },
  { id: '38', name: 'Budget', color: '#EF4444', icon: DollarSign },
  { id: '39', name: 'Timesheet', color: '#F97316', icon: Timer },
  { id: '40', name: 'Training', color: '#06B6D4', icon: GraduationCap },
  { id: '41', name: 'Certificate', color: '#8B5CF6', icon: Award },
  { id: '42', name: 'Feedback', color: '#22C55E', icon: MessageCircle }
];